AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create an FSx for Windows file system. [v1.0]
Parameters:
  VPCID:
    Description: VPC ID for Storage Gateway
    Type: AWS::EC2::VPC::Id
  DirectoryId:
    Description: The ID for an existing AWS Managed Microsoft Active Directory (AD) instance that the file system should join when it's created.
    Type: String
    AllowedPattern: "^d-[0-9a-f]{10}$"
  FileSystemSize:
    Description: The storage capacity of the file system being created. 32 GiB - 65,536 GiB (64 TiB)
    Type: Number
    Default: 32
    MinValue: 32
    MaxValue: 65536
  FSxThroughput:
    Description: >
      The throughput capacity of an Amazon FSx file system, measured in megabytes per second 
      in powers of 2 (8, 16, 32, ... , 1024), with the recommended value based on the file 
      system size: 8 for <800 GiB, 16 for <1600 GiB, ... 512 for <51200 GiB, 1024 for >=51200 GiB
    Type: Number
    AllowedValues:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
      - 512
      - 1024
      - 2048
  AZDeploymentMode:
    Description: "Specifies the file system deployment type"
    Type: String
    Default: SINGLE_AZ_2
    AllowedValues:
      - SINGLE_AZ_2
      - MULTI_AZ_1
  PrimarySubnetAccess:
    Description: Specifies the primary subnet that the file system will be accessible from
    Type: AWS::EC2::Subnet::Id
  SecondarySubnetAccess:
    Description: Specifies the subnets that the file system will be accessible from
    Type: AWS::EC2::Subnet::Id
  Project:
    Description: Tag used for resources and billing
    Type: String
    Default: cloud-edit-fsx
  DomainMemberSGID:
    Description: ID of the Domain Member Security Group (e.g., sg-7f16e910)
    Type: AWS::EC2::SecurityGroup::Id
  
Conditions:
  MultiAZ: !Equals [!Ref AZDeploymentMode, MULTI_AZ_1]

Resources:
  FSXBaseSG:
    Type: "AWS::EC2::SecurityGroup"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W5
            reason: "Using open egress so that FSX has full internet access"
          - id: W29
            reason: "Using open egress so that FSX has full internet access"
          - id: W27
            reason: "Port range required for Certificate Management over CMS"
          - id: W9
            reason: "Security Groups needs to be /16 to cover IP ranges in VPC"
    Properties:
      GroupDescription: Base Security Group for SecGrp
      VpcId: !Ref VPCID
      SecurityGroupEgress:
        - IpProtocol: udp
          Description: "All UDP Traffic"
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          Description: "All TCP Traffic"
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          Description: "DNS"
          CidrIp: 10.0.0.0/16
          FromPort: 53
          ToPort: 53
        - IpProtocol: udp
          Description: "DNS"
          CidrIp: 10.0.0.0/16
          FromPort: 53
          ToPort: 53
        - IpProtocol: udp
          Description: "Kerberos"
          CidrIp: 10.0.0.0/16
          FromPort: 88
          ToPort: 88
        - IpProtocol: tcp
          Description: "Kerberos"
          CidrIp: 10.0.0.0/16
          FromPort: 88
          ToPort: 88
        - IpProtocol: udp
          Description: "NTP"
          CidrIp: 10.0.0.0/16
          FromPort: 123
          ToPort: 123
        - IpProtocol: tcp
          Description: "NTP"
          CidrIp: 10.0.0.0/16
          FromPort: 135
          ToPort: 135
        - IpProtocol: udp
          Description: "LDAP"
          CidrIp: 10.0.0.0/16
          FromPort: 389
          ToPort: 389
        - IpProtocol: tcp
          Description: "LDAP"
          CidrIp: 10.0.0.0/16
          FromPort: 389
          ToPort: 389
        - IpProtocol: udp
          Description: "Microsoft AD"
          CidrIp: 10.0.0.0/16
          FromPort: 445
          ToPort: 445
        - IpProtocol: tcp
          Description: "Microsoft AD"
          CidrIp: 10.0.0.0/16
          FromPort: 445
          ToPort: 445
        - IpProtocol: udp
          Description: "Kerberos Change/Set password"
          CidrIp: 10.0.0.0/16
          FromPort: 464
          ToPort: 464
        - IpProtocol: tcp
          Description: "Kerberos Change/Set password"
          CidrIp: 10.0.0.0/16
          FromPort: 464
          ToPort: 464
        - IpProtocol: tcp
          Description: "LDAPS"
          CidrIp: 10.0.0.0/16
          FromPort: 636
          ToPort: 636
        - IpProtocol: tcp
          Description: "Microsoft Global Catalog"
          CidrIp: 10.0.0.0/16
          FromPort: 3268
          ToPort: 3269
        - IpProtocol: tcp
          Description: "Microsoft AD DS Web Services"
          CidrIp: 10.0.0.0/16
          FromPort: 9389
          ToPort: 9389
        - IpProtocol: tcp
          Description: "Certificate Management over CMS"
          CidrIp: 10.0.0.0/16
          FromPort: 49152
          ToPort: 65535
  DomainMembersSGIngressUDP:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: "Base Security Group for UDP Ingress"
      GroupId: !Ref DomainMemberSGID
      IpProtocol: udp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !GetAtt FSXBaseSG.GroupId
  DomainMembersSGIngressTCP:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: "Base Security Group for TCP Ingress"
      GroupId: !Ref DomainMemberSGID
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !GetAtt FSXBaseSG.GroupId
  FSxFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: WINDOWS
      SecurityGroupIds:
        - !Ref DomainMemberSGID
        - !GetAtt "FSXBaseSG.GroupId"
      StorageCapacity: !Ref FileSystemSize
      SubnetIds:
        - !Ref PrimarySubnetAccess
        - !If [MultiAZ, !Ref SecondarySubnetAccess, !Ref "AWS::NoValue"]
      Tags:
        - Key: Name
          Value: !Sub "${Project}-FSx"
      WindowsConfiguration:
        ActiveDirectoryId: !Ref DirectoryId
        AutomaticBackupRetentionDays: 0
        DeploymentType: !Ref AZDeploymentMode
        PreferredSubnetId:
          !If [MultiAZ, !Ref PrimarySubnetAccess, !Ref "AWS::NoValue"]
        ThroughputCapacity: !Ref FSxThroughput

Outputs:
  FSXSecurityGroup:
    Value: !Ref "FSXBaseSG"
    Description: Security group for the FSX FileSystem created
  FSxFileSystem:
    Value: !Ref "FSxFileSystem"
    Description: The FSX FileSystem Created